// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cinema struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	City      string       `json:"city"`
	Address   string       `json:"address"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Movie struct {
	ID              uuid.UUID    `json:"id"`
	Title           string       `json:"title"`
	DurationMinutes int32        `json:"duration_minutes"`
	Rating          string       `json:"rating"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Showtime struct {
	ID        uuid.UUID    `json:"id"`
	MovieID   uuid.UUID    `json:"movie_id"`
	StudioID  uuid.UUID    `json:"studio_id"`
	StartTime time.Time    `json:"start_time"`
	EndTime   time.Time    `json:"end_time"`
	Price     string       `json:"price"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Studio struct {
	ID         uuid.UUID    `json:"id"`
	CinemaID   uuid.UUID    `json:"cinema_id"`
	Name       string       `json:"name"`
	TotalSeats int32        `json:"total_seats"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FullName     string       `json:"full_name"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
