// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckShowtimeOverlap(ctx context.Context, arg CheckShowtimeOverlapParams) (int64, error)
	CreateShowtime(ctx context.Context, arg CreateShowtimeParams) (Showtime, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteShowtime(ctx context.Context, id uuid.UUID) error
	GetShowtimeByID(ctx context.Context, id uuid.UUID) (GetShowtimeByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListShowtimes(ctx context.Context, arg ListShowtimesParams) ([]ListShowtimesRow, error)
	UpdateShowtime(ctx context.Context, arg UpdateShowtimeParams) (Showtime, error)
}

var _ Querier = (*Queries)(nil)
