// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: showtimes.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkShowtimeOverlap = `-- name: CheckShowtimeOverlap :one
SELECT COUNT(*) FROM showtimes
WHERE studio_id = $1
  AND id != $2
  AND status != 'CANCELLED'
  AND (start_time < $4 AND end_time > $3)
`

type CheckShowtimeOverlapParams struct {
	StudioID  uuid.UUID `json:"studio_id"`
	ID        uuid.UUID `json:"id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) CheckShowtimeOverlap(ctx context.Context, arg CheckShowtimeOverlapParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkShowtimeOverlap,
		arg.StudioID,
		arg.ID,
		arg.EndTime,
		arg.StartTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShowtime = `-- name: CreateShowtime :one
INSERT INTO showtimes (
    id, movie_id, studio_id, start_time, end_time, price, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, movie_id, studio_id, start_time, end_time, price, status, created_at, updated_at
`

type CreateShowtimeParams struct {
	ID        uuid.UUID `json:"id"`
	MovieID   uuid.UUID `json:"movie_id"`
	StudioID  uuid.UUID `json:"studio_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Price     string    `json:"price"`
	Status    string    `json:"status"`
}

func (q *Queries) CreateShowtime(ctx context.Context, arg CreateShowtimeParams) (Showtime, error) {
	row := q.db.QueryRowContext(ctx, createShowtime,
		arg.ID,
		arg.MovieID,
		arg.StudioID,
		arg.StartTime,
		arg.EndTime,
		arg.Price,
		arg.Status,
	)
	var i Showtime
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.StudioID,
		&i.StartTime,
		&i.EndTime,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShowtime = `-- name: DeleteShowtime :exec
UPDATE showtimes
SET 
    status = 'CANCELLED',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteShowtime(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShowtime, id)
	return err
}

const getShowtimeByID = `-- name: GetShowtimeByID :one
SELECT 
    s.id, s.movie_id, s.studio_id, s.start_time, s.end_time, s.price, s.status, s.created_at, s.updated_at,
    m.title AS movie_title, m.duration_minutes AS movie_duration, m.rating AS movie_rating,
    st.name AS studio_name,
    c.name AS cinema_name
FROM showtimes s
JOIN movies m ON s.movie_id = m.id
JOIN studios st ON s.studio_id = st.id
JOIN cinemas c ON st.cinema_id = c.id
WHERE s.id = $1 LIMIT 1
`

type GetShowtimeByIDRow struct {
	ID            uuid.UUID    `json:"id"`
	MovieID       uuid.UUID    `json:"movie_id"`
	StudioID      uuid.UUID    `json:"studio_id"`
	StartTime     time.Time    `json:"start_time"`
	EndTime       time.Time    `json:"end_time"`
	Price         string       `json:"price"`
	Status        string       `json:"status"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
	MovieTitle    string       `json:"movie_title"`
	MovieDuration int32        `json:"movie_duration"`
	MovieRating   string       `json:"movie_rating"`
	StudioName    string       `json:"studio_name"`
	CinemaName    string       `json:"cinema_name"`
}

func (q *Queries) GetShowtimeByID(ctx context.Context, id uuid.UUID) (GetShowtimeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getShowtimeByID, id)
	var i GetShowtimeByIDRow
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.StudioID,
		&i.StartTime,
		&i.EndTime,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MovieTitle,
		&i.MovieDuration,
		&i.MovieRating,
		&i.StudioName,
		&i.CinemaName,
	)
	return i, err
}

const listShowtimes = `-- name: ListShowtimes :many
SELECT 
    s.id, s.movie_id, s.studio_id, s.start_time, s.end_time, s.price, s.status, s.created_at, s.updated_at,
    m.title AS movie_title, m.duration_minutes AS movie_duration, m.rating AS movie_rating,
    st.name AS studio_name,
    c.name AS cinema_name
FROM showtimes s
JOIN movies m ON s.movie_id = m.id
JOIN studios st ON s.studio_id = st.id
JOIN cinemas c ON st.cinema_id = c.id
WHERE s.status != 'CANCELLED'
ORDER BY s.start_time ASC
LIMIT $1 OFFSET $2
`

type ListShowtimesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListShowtimesRow struct {
	ID            uuid.UUID    `json:"id"`
	MovieID       uuid.UUID    `json:"movie_id"`
	StudioID      uuid.UUID    `json:"studio_id"`
	StartTime     time.Time    `json:"start_time"`
	EndTime       time.Time    `json:"end_time"`
	Price         string       `json:"price"`
	Status        string       `json:"status"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
	MovieTitle    string       `json:"movie_title"`
	MovieDuration int32        `json:"movie_duration"`
	MovieRating   string       `json:"movie_rating"`
	StudioName    string       `json:"studio_name"`
	CinemaName    string       `json:"cinema_name"`
}

func (q *Queries) ListShowtimes(ctx context.Context, arg ListShowtimesParams) ([]ListShowtimesRow, error) {
	rows, err := q.db.QueryContext(ctx, listShowtimes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShowtimesRow
	for rows.Next() {
		var i ListShowtimesRow
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.StudioID,
			&i.StartTime,
			&i.EndTime,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MovieTitle,
			&i.MovieDuration,
			&i.MovieRating,
			&i.StudioName,
			&i.CinemaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShowtime = `-- name: UpdateShowtime :one
UPDATE showtimes
SET 
    movie_id = $2,
    studio_id = $3,
    start_time = $4,
    end_time = $5,
    price = $6,
    status = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, movie_id, studio_id, start_time, end_time, price, status, created_at, updated_at
`

type UpdateShowtimeParams struct {
	ID        uuid.UUID `json:"id"`
	MovieID   uuid.UUID `json:"movie_id"`
	StudioID  uuid.UUID `json:"studio_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Price     string    `json:"price"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateShowtime(ctx context.Context, arg UpdateShowtimeParams) (Showtime, error) {
	row := q.db.QueryRowContext(ctx, updateShowtime,
		arg.ID,
		arg.MovieID,
		arg.StudioID,
		arg.StartTime,
		arg.EndTime,
		arg.Price,
		arg.Status,
	)
	var i Showtime
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.StudioID,
		&i.StartTime,
		&i.EndTime,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
